version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/jenkins"
      - "/keycloak"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directories:
      - "/dcm4chee"
      - "/grafana"
      - "/minio"
      - "/otel"
      - "/traefik"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "dcm4che/slapd-dcm4chee"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "dcm4che/postgres-dcm4chee"
        versions: [">= 17.0.0"]
      - dependency-name: "dcm4che/dcm4chee-arc-psql"
        versions: [">= 5.33.0"]
