version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/jenkins"
      - "/keycloak"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directories:
      - "/dcm4chee"
      - "/grafana"
      - "/minio"
      - "/otel"
      - "/traefik"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "dcm4che/slapd-dcm4chee"
        versions: ["3.x.x", "4.x.x", "5.x.x"]
