version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/jenkins"
      - "/keycloak"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directories:
      - "/dcm4chee"
      - "/grafana"
      - "/otel"
      - "/traefik"
    schedule:
      interval: "weekly"
