services:
  keycloak:
    container_name: keycloak_sotamed
    image: sotamed-keycloak:0.1.0
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "6102:8080"
      #- "6200:8443"
      - "6500:9000"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB_URL_HOST=keycloak_db
      - KC_DB_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY_HEADERS=xforwarded
    volumes:
      - ./realms:/opt/keycloak/data/import
      - ./themes:/opt/keycloak/providers/
    command: start --hostname=https://keycloak.sotatek.works --optimized --import-realm
    networks:
      - db_net
      - keycloak_net

  db:
    image: postgres:17.5
    container_name: keycloak_db
    restart: always
    shm_size: 128mb
    ports:
      - "5004:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - db_net
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:

networks:
  db_net:
  keycloak_net:
    name: keycloak_net
