services:
  keycloak:
    container_name: keycloak_sotamed
    image: sotamed-keycloak:0.0.1
    build:
      context: .
    restart: unless-stopped
    ports:
      # - "6102:8080"
      - "6102:8443"
      - "6500:9000"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB_URL_HOST=keycloak_db
      - KC_DB_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HTTP_ENABLED=true
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_FRONTEND_URL=https://keycloak.sotatek.works
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HOSTNAME_ADMIN_URL=https://keycloak.sotatek.works
        #- KC_HTTPS_CERTIFICATE_FILE=/certs/wildcard.sotatek.works.crt
        #- KC_HTTPS_CERTIFICATE_KEY_FILE=/certs/wildcard.sotatek.works.key
    command: start --optimized --hostname=keycloak.sotatek.works --proxy-headers=xforwarded
    networks:
      - db_net
      # - traefik_net
    volumes:
      - ./certs:/certs
    # labels:
    #   - "traefik.enable=true"
    #   # HTTP
    #   - "traefik.http.routers.keycloak.entrypoints=http"
    #   - "traefik.http.routers.keycloak.rule=Host(`keycloak.sotatek.works`)"
    #   - "traefik.http.routers.keycloak.middlewares=redirect-https@file"
    #   # HTTPS
    #   - "traefik.http.routers.keycloak-https.entrypoints=https"
    #   - "traefik.http.routers.keycloak-https.rule=Host(`keycloak.sotatek.works`)"
    #   - "traefik.http.routers.keycloak-https.tls=true"
    #   - "traefik.http.services.keycloak-https.loadbalancer.server.port=8080"

  db:
    image: postgres:17.5
    container_name: keycloak_db
    restart: always
    shm_size: 128mb
    ports:
      - "5004:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - db_net
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:

networks:
  db_net:
  # traefik_net:
  #   external: true
