services:
  grafana:
    container_name: grafana_sotamed
    image: grafana/grafana:12.1.1
    networks:
      - grafana_net
    ports:
      - "6502:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./dashboards:/etc/grafana/dashboards
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources

  loki:
    container_name: loki_sotamed
    image: grafana/loki:3.5.3
    networks:
      - grafana_net
      - loki_net
    ports:
      - "6600:3100"
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    container_name: tempo_sotamed
    image: grafana/tempo:2.8.2
    networks:
      - grafana_net
      - tempo_net
    ports:
      - "3200:3200"   # Tempo query API (optional for Grafana)
      - "4317:4317"   # OTLP/gRPC
      - "4318:4318"   # OTLP/HTTP
    command: "-config.file=/etc/tempo/tempo.yaml"
    volumes:
      - ./tempo:/etc/tempo
      - tempo-data:/tmp/tempo

volumes:
  grafana-storage:
  tempo-data:

networks:
  grafana_net:
    name: grafana_net
  loki_net:
    name: loki_net
  tempo_net:
    name: tempo_net