services:
  grafana:
    container_name: grafana_sotamed
    image: grafana/grafana:12.1.0
    ports:
      - "30000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    container_name: loki_sotamed
    image: grafana/loki:3.5.1
    ports:
      - "31000:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  grafana-storage:
