## Dynamic configuration
http:
  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/config/wildcard.sotamed.internal.crt"
        keyFile: "/config/wildcard.sotamed.internal.key"
  certificates:
    - certFile: "/config/wildcard.sotamed.internal.crt"
      keyFile: "/config/wildcard.sotamed.internal.key"
      stores:
        - default
