services:
  agent-1:
    container_name: teamcity_agent
    image: teamcity-agent:0.0.2
    build:
      context: .
    restart: unless-stopped
    user: root
    environment:
      SERVER_URL: http://10.4.40.187:6100
    networks:
      - teamcity_net
    volumes:
      - ./conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:

networks:
  teamcity_net:
    external: true
