services:
  jenkins:
    container_name: jenkins-blueocean
    image: sotamed-jenkins:0.0.6
    build:
      context: .
    restart: unless-stopped
    user: root
    networks:
      - jenkins_net
      # - traefik_net
    ports:
      - "6101:8080"
      - "50000:50000"
    volumes:
      - data:/var/jenkins_home
      - /tmp/jenkins:/tmp/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    # labels:
    #   - "traefik.enable=true"
    #   # HTTP
    #   - "traefik.http.routers.jenkins.rule=Host(`jenkins.sotatek.works`)"
    #   - "traefik.http.routers.jenkins.entrypoints=http"
    #   - "traefik.http.routers.jenkins.middlewares=redirect-https@file"
    #   # HTTPS
    #   - "traefik.http.routers.jenkins-https.rule=Host(`jenkins.sotatek.works`)"
    #   - "traefik.http.routers.jenkins-https.entrypoints=https"
    #   - "traefik.http.routers.jenkins-https.tls=true"
    #   - "traefik.http.services.jenkins.loadbalancer.server.port=6101"
    #   # TCP
    #   - "traefik.tcp.routers.jenkins.rule=HostSNI(`jenkins.sotatek.works`)"
    #   - "traefik.tcp.routers.jenkins.tls=true"
    #   - "traefik.tcp.services.jenkins.loadbalancer.server.port=50000"

volumes:
  data:

networks:
  jenkins_net:
    external: true
  # traefik_net:
  #   external: true
