services:
  jenkins:
    container_name: jenkins-blueocean
    image: sotamed-jenkins:0.0.6
    build:
      context: .
    restart: unless-stopped
    user: root
    networks:
      - jenkins_net
    ports:
      - "6101:8080"
      - "50000:50000"
    volumes:
      - data:/var/jenkins_home
      - /tmp/jenkins:/tmp/jenkins
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  data:

networks:
  jenkins_net:
    external: true
