services:
  ldap:
    container_name: pacs_dcm4chee_ldap
    image: dcm4che/slapd-dcm4chee:2.6.8-34.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    # ports:
    #   - "389:389"
    environment:
      STORAGE_DIR: /storage/fs1
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_slapd_data:/etc/ldap/slapd.d
    networks:
      - dcm4chee_network

  db:
    container_name: pacs_dcm4chee_db
    image: dcm4che/postgres-dcm4chee:16.2-32
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5005:5432"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - db_data:/var/lib/postgresql/data
    networks:
      - dcm4chee_network

  arc:
    container_name: pacs_dcm4chee_arc
    image: dcm4che/dcm4chee-arc-psql:5.32.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "7101:8080" # HTTP
      - "7200:8443" # HTTPS
      # - "9990:9990"
      # - "9993:9993"
      - "7300:11112" # DICOM
      - "7400:2762" # DICOM secured
      - "7500:2575" # HL7
      - "7600:12575" # HL7 secured
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - arc_wildfly_data:/opt/wildfly/standalone
      - arc_storage_data:/storage
    networks:
      - dcm4chee_network

volumes:
  ldap_data:
  ldap_slapd_data:
  db_data:
  arc_wildfly_data:
  arc_storage_data:

networks:
  dcm4chee_network:
    name: dcm4chee_network
  # traefik_net:
  #   external: true
