services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.3-29.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - ~/dcm4chee-arc/ldap:/var/lib/ldap
      - ~/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
    networks:
      - dcm4chee_network

  db:
    image: dcm4che/postgres-dcm4chee:14.5-29
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/dcm4chee-arc/db:/var/lib/postgresql/data
    networks:
      - dcm4chee_network

  arc:
    image: dcm4che/dcm4chee-arc-psql:5.29.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080" # HTTP
      - "8443:8443" # HTTPS
      # - "9990:9990"
      # - "9993:9993"
      - "11112:11112" # DICOM
      - "2762:2762"   # DICOM secured
      - "2575:2575"   # HL7
      - "12575:12575" # HL7 secured
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - ~/dcm4chee-arc/storage:/storage
    networks:
      - dcm4chee_network

networks:
  dcm4chee_network: