services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    restart: always
    ports:
      - "6000:9000"
      - "6501:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "123@1234"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - minio_net

volumes:
  minio_data:

networks:
  minio_net:
    name: minio_net
