services:
  minio:
    container_name: minio
    image: sotamed-minio:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6000:9000"
      - "6501:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "123@1234"
      MINIO_ALIAS_URL: http://10.4.40.187:6000
    volumes:
      - minio_data:/data
    networks:
      - minio_net

volumes:
  minio_data:

networks:
  minio_net:
    name: minio_net
